version: "3.8"

services:
  postgres:
    container_name: postgres
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - main
    env_file:
      - .env
    volumes:
      - ./postgres_data:/data

  api:
    container_name: api
    restart: always
    build: .
    expose:
      - 8000
    volumes:
      - .:/code/app
    depends_on:
      - postgres
    command: sh -c "uvicorn main:app --workers 4 --proxy-headers --host 0.0.0.0 --port 8000"
    networks:
      - main

networks:
  main:
